### ISSUE TITLE
Doesn't load into Brave on Ubuntu 20.04

### ISSUE THREAD

**Issue by Raffles727** [miamiww/Big-Tech-Detective#19]
![Screenshot from 2021-02-27 08-16-25](https://user-images.githubusercontent.com/29001558/109381802-589cc100-78d4-11eb-8c9e-51257b6ed8af.png)

Does this work in Brave? (Ubuntu 20.04)

It fails to load with error "Manifest file is missing or unreadable"

**Comment by miamiww** [comment]
It works in Brave for me on Mojave. If the manifest file is unreadable the zip file may have gotten corrupted on download, try redownloading and let me know if the issue persists.

**Comment by Raffles727** [comment]
It's working now thanks. You can close the issue. The problem was that I tried to load the parent folder "BTDchrome_1.0.0" , but it's the file "chrome" inside the parent folder that should be loaded

**Comment by lemaximedu66** [comment]
ok can you close this pls? thanks!
